### ISSUE TITLE
TypeError: 'MultiPoint' object is not iterable

### ISSUE THREAD

**Issue by wuliRothschild** [illuminate6060/SpotGF#2]
I came across the following problem when I ran calculate_GFscore function:

GF_df = spotgf.calculate_GFscore(gem_path,binsize)
Calculate SpotGF scores for genes with binsize  77
Process with Bin 77 data
Genes Number: 15099
Cells number: 4
Traceback (most recent call last):

  File "C:\Users\wulir\AppData\Local\Temp\ipykernel_23356\2670899550.py", line 1, in <module>
    GF_df = spotgf.calculate_GFscore(gem_path,binsize)

  File "C:\Personal Files\Python\spotgfanalysis\SpotGF\SpotGF.py", line 201, in calculate_GFscore
    result = self.calculate_ot(all_gene,ex2,all_cell)

  File "C:\Personal Files\Python\spotgfanalysis\SpotGF\SpotGF.py", line 135, in calculate_ot
    alpha = alphashape.optimizealpha(all_cell)

  File "C:\miniconda\envs\SpotGF\lib\site-packages\alphashape\optimizealpha.py", line 100, in optimizealpha
    if _testalpha(points, test_alpha):

  File "C:\miniconda\envs\SpotGF\lib\site-packages\alphashape\optimizealpha.py", line 41, in _testalpha
    return all([polygon.intersects(point) for point in points])

TypeError: 'MultiPoint' object is not iterable

How can I solve this?
Thanks.

**Comment by illuminate6060** [comment]
I see that your number of cells is only 4, I am worried that 4 cells cannot identify valid tissue boundaries, I suggest you reduce the binsize parameter. If you still have this error, please don't hesitate to contact me

**Comment by wuliRothschild** [comment]
Thank you for your insightful guidance; I indeed misunderstood the meaning of the parameter binsize, which led to the use of an incorrect value.

I have two 10X Visium spatial transcriptomics datasets, each sample containing approximately 4900 spots. My understanding is that, unlike Stereo-seq, Visium has a much lower resolution, implying that each spot has a large radius and contains many cells, so the binsize should be set very low, even to 1.

Initially, I tried setting the parameter to 4 or 5, but the error persisted. When I reduced the parameter to 2, one sample ran successfully. When I set the parameter to 1, the other sample also ran successfully, but the analysis of the previous sample indicated that the maximum number of iterations was reached, potentially yielding inaccurate results. I then set the maximum number of iterations to 1,000,000, and the analysis of both samples was completed successfully.

Additionally, I have another question: How should I set the proportion parameter for filtering? For the aforementioned analysis samples, I used the automatic threshold setting option. One sample's expression matrix was identical to the input file, while the other sample's expression matrix removed over 95% of the UMI counts, making the downstream analysis nearly impossible. Is there an issue with my parameter settings causing unstable results?

My parameter usage is as follows:
```plaintext
gem_path = './Output/SpotGF/Preprocess/spo.gem'
output = "."
binsize = 1
lower = 0
upper = 100000
proportion = 0.6
max_iterations = 100000
auto_threshold = True
```
Thank you very much for developing this interesting tool and for your guidance.

**Comment by illuminate6060** [comment]
I am very sorry for the late reply. Thank you for testing and using.
Recently, i updated a new version of SpotGF which has added more personalized parameter options and reasonable visualization results. Welcome to use it. The bug has been fixed in the new version. If you still encounter the following problem, please do not hesitate to contact me:
IndexError: index 2 is out of bounds for axis 0 with size 2

If the number of denoised data genes based on automatic thresholds is too small, it can first be indicated that the noise level of the data is a little high. In this case, the data automatically denoised cannot be used, and the proportion can be customized. I recommend that it is reasonable to retain at least 2,000 to 5,000 genes for the data filtered based on proportion.
